### ISSUE TITLE
[FEATURE] Support for fsspec file caching in catalog sources

### ISSUE THREAD

**Issue by adrianloy** [merantix-momentum/squirrel-core#214]
Squirrel currently does not support using filecache or simple cache protocol.

Reproducible example:
catalog.yaml:
```
!YamlCatalog
version: 0.20.1
- !YamlSource
  identifier: some_ds_name
  driver_name: messagepack
  driver_kwargs:
    url: gs://some_bucket/datasets/messagepack_files
#    url: filecache:gs://some_bucket/datasets/messagepack_files  # should work, but doesnt due to get_fs_from_url
    storage_options:
      protocol: "simplecache"
      cache_storage: "/tmp/files"
      target_protocol: "gs"
```
Trying to load this data source via `catalog.from_yaml('catalog.yaml').get_driver().get_iter().take(1).collect()` fails with
```
AttributeError: 'dict' object has no attribute 'startswith'
```
As we try to do `urls.sort` in `source.py` FIlePathGenerator, but the cached filesystem returns dictionaries instead of strings, which cannot be sorted.
